### ISSUE TITLE
[Error] [SSL: WRONG_VERSION_NUMBER]

### ISSUE THREAD

**Issue by Oshannk** [miyurudassanayake/ssh-tls-ssl-sni-injector-to-socks5#3]
I am getting this error from the server, does anyone know how to fix this?

> [Error] [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)

**Comment by miyurudassanayake** [comment]
what server os did you use?

**Comment by Oshannk** [comment]
> what server os did you use?

Ubuntu 20.04 LTS x64 (Digital Ocean)

After creating the droplet, what are the steps to be done on the server side?

**Comment by hazimmtaru** [comment]
> what server os did you use?

Hey, i don't know much about this stuff, wanted to try this repo, how can i get a ssh server?

**Comment by abdoxfox** [comment]
At least you have to mention from where yo stolen the code

**Comment by miyurudassanayake** [comment]
> > what server os did you use?
> 
> Hey, i don't know much about this stuff, wanted to try this repo, how can i get a ssh server?

This is the client-side code. You need to launch a Linux server that has SSH, and you need to install stunnel to wrap the connection. For a more in-depth understanding, check out this link: [Setting Up an SSL Tunnel using stunnel on Ubuntu](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-ssl-tunnel-using-stunnel-on-ubuntu).

**Comment by roxzshakeer** [comment]
does this works for free rated sites in sri lanka. Especially dialog.

**Comment by miyurudassanayake** [comment]
> does this works for free rated sites in sri lanka. Especially dialog.

Yes
