### ISSUE TITLE
How to connect with ssh Host, Port, username, pass, custom payload and HTTP proxy with port.

### ISSUE THREAD

**Issue by abhishekcs0** [miyurudassanayake/ssh-tls-ssl-sni-injector-to-socks5#5]
Hey, I have set up a aws server and using free internet with these above mentioned info from server on HTTP INJECTOR android application, I am searching  a soulution to use this on linux didn't found any working method , I am new to linux, is there any app like android http injector ?

**Comment by kirula0626** [comment]
For Linux use proxychains
apt-get install proxychains4
or 
add local host ip and port to socks5

**Comment by abhishekcs0** [comment]
thanks for info, actually I found the alternate to this, used NekoRay with Vmess and was able to connect to my server
