### ISSUE TITLE
Learning material

### ISSUE THREAD

**Issue by Wkrotik** [miyurudassanayake/ssh-tls-ssl-sni-injector-to-socks5#7]
Hey, I know nothing about networking

can I read somewhere how this works more in detail? and I could not set it up for myself, help is appreciated. thanks

**Comment by miyurudassanayake** [comment]
I couldn't find any direct resources related to this, but I'd suggest starting with basic networking concepts, especially focusing on SSL/TLS handshakes and how SNI (Server Name Indication) works. Once you have a good understanding of these, you'll find it easier to grasp how the SNI modification works in the code and how it interacts with proxies and firewalls.
