### ISSUE TITLE
[Error] [WinError 10060] 

### ISSUE THREAD

**Issue by Zack00e** [miyurudassanayake/ssh-tls-ssl-sni-injector-to-socks5#8]
C:\Users\username\Desktop\sni-injector-master>py main.py
Waiting for incoming connection to : 127.0.0.1:9092

ssh -C -o "ProxyCommand=ncat --proxy 127.0.0.1:9092 %h %p" username@ip -p 443 -CND 1080 -o StrictHostKeyChecking=no -o UserKnownHostsFile=nul

[*] New Client connected!
[TCP] connected to ip:443
[Error] [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

my settings.ini file: 

[settings]
local_ip = 127.0.0.1
listen_port = 9092

[ssh]
host = ip

[sni]
server_name = facebook.com

**Comment by miyurudassanayake** [comment]
The error is likely caused by missing or incorrect details in your settings.ini file. Make sure you fill in all the required fields with accurate information.
